import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  detectionText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  permissionText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  permissionButton: {
    backgroundColor: "#10ac84",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
  },
  permissionButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  camera: { flex: 1 },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderColor: "#eee",
    paddingTop: 40,
  },
  modalTitle: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#222",
  },
  modalScrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  modalImageContainer: {
    marginBottom: 24,
    alignItems: "center",
    position: "relative",
  },
  modalImage: {
    width: 220,
    height: 300,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  modalRemoveButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 15,
    padding: 2,
  },
  modalImageLabel: {
    marginTop: 8,
    color: "#333",
    fontWeight: "500",
  },
  modalFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderColor: "#eee",
    flexDirection: "row",
    gap: 12,
  },
  modalButton: {
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    paddingTop: 10,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginLeft: 15,
  },
  titleInput: {
    fontSize: 16,
    color: "#333",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 8,
    paddingHorizontal: 5,
  },
  emptyListText: {
    textAlign: "center",
    marginTop: 50,
    fontSize: 16,
    color: "#888",
  },
  listItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "#f9f9f9",
    padding: 8,
    borderRadius: 8,
  },
  listItemImage: {
    width: 60,
    height: 85,
    borderRadius: 6,
    marginRight: 12,
  },
  listItemLabel: {
    flex: 1,
    fontSize: 15,
    color: "#444",
  },
  listItemRemove: {
    padding: 5,
  },
  processingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  processingText: {
    marginTop: 20,
    color: "#333",
    fontSize: 16,
    marginBottom: 15,
  },
  progressBarContainer: {
    width: "80%",
    height: 10,
    backgroundColor: "#eee",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#10ac84",
    borderRadius: 5,
  },
  progressText: {
    marginTop: 10,
    color: "#666",
    marginBottom: 20,
  },
  successContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#10ac84",
    marginBottom: 10,
    textAlign: "center",
  },
  successSubtitle: {
    fontSize: 16,
    color: "#333",
    marginBottom: 30,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  successButton: {
    backgroundColor: "#10ac84",
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
  },
  successButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  titleScreenContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
  },
  titleCard: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
  },
  titleIcon: {
    alignSelf: "center",
    marginBottom: 15,
  },
  titleScreenHeading: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 5,
  },
  titleScreenSubheading: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
  },
  titleScreenInput: {
    height: 50,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    fontSize: 16,
    marginBottom: 20,
  },
  previewImagesContainer: {
    marginBottom: 20,
  },
  previewLabel: {
    fontSize: 14,
    color: "#333",
    marginBottom: 5,
  },
  previewScrollContainer: {
    paddingVertical: 10,
  },
  previewThumbnail: {
    width: 100,
    height: 140,
    borderRadius: 5,
    marginRight: 10,
  },
  saveDocumentButton: {
    backgroundColor: "#10ac84",
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: "center",
  },
  saveDocumentButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  actionButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 25,
    minWidth: 100,
  },
  actionButtonText: {
    color: "#fff",
    fontWeight: "600",
    marginLeft: 8,
    fontSize: 15,
  },
  saveButton: {
    backgroundColor: "#10ac84",
  },
  disabledButton: {
    backgroundColor: "#a0a0a0",
    opacity: 0.7,
  },
  backgroundProcessButton: {
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    backgroundColor: "#10ac84",
  },
  backgroundProcessText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },

  // Model loading and warning styles
  loadingText: {
    fontSize: 18,
    fontWeight: "500",
    marginTop: 15,
    textAlign: "center",
    color: "#10ac84",
  },
  loadingSubText: {
    fontSize: 14,
    color: "#666",
    marginTop: 8,
    textAlign: "center",
  },
  modelWarningBanner: {
    position: "absolute",
    top: 40,
    left: 0,
    right: 0,
    backgroundColor: "rgba(243, 156, 18, 0.9)",
    padding: 10,
    zIndex: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modelWarningText: {
    color: "#fff",
    marginLeft: 8,
    fontSize: 14,
    fontWeight: "500",
    flexShrink: 1,
  },
  modelWarningCard: {
    backgroundColor: "#fff8e1",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffeeba",
  },
  modelWarningCardText: {
    color: "#856404",
    marginLeft: 10,
    fontSize: 14,
    flex: 1,
  },
  previewTabContainer: {
    flexDirection: "row",
    marginTop: 20,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    width: "100%",
  },
  previewTab: {
    paddingVertical: 8,
    paddingHorizontal: 24,
    marginRight: 10,
    borderBottomWidth: 0,
  },
  activePreviewTab: {
    borderBottomWidth: 2,
    borderBottomColor: "#10ac84",
  },
  previewTabText: {
    color: "#666",
    fontWeight: "bold",
  },
  activePreviewTabText: {
    color: "#10ac84",
  },
  previewContent: {
    width: "100%",
    height: 350,
    marginVertical: 10,
  },
  imagePreviewContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  textPreviewContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  imagePreviewPage: {
    width: Dimensions.get("window").width * 0.8,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  textPreviewPage: {
    width: Dimensions.get("window").width * 0.8,
    alignItems: "center",
    padding: 10,
    height: 300,
  },
  previewImage: {
    width: 240,
    height: 320,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
  },
  textScrollView: {
    maxHeight: 240,
    width: "100%",
    marginBottom: 10,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    padding: 12,
  },
  previewText: {
    fontSize: 14,
    color: "#333",
  },
  pageIndicatorText: {
    marginTop: 8,
    color: "#666",
    fontWeight: "500",
  },
  paginationText: {
    marginTop: 5,
    color: "#666",
  },
  textActionsContainer: {
    flexDirection: "row",
    marginTop: 5,
    justifyContent: "center",
    width: "100%",
    gap: 15,
  },
  copyButton: {
    backgroundColor: "#10ac84",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 6,
  },
  copyAllButton: {
    backgroundColor: "#2d3436",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 6,
  },
  copyButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
});
